services:
  postgres_db:
    image: postgres:15-alpine
    container_name: slaccesorios_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword # OJO: Antes de ir a prod, esto lo pasaremos a un archivo .env que no se sube a GitHub
      POSTGRES_DB: slaccesorios_db
    ports:
      - "55432:5432" # ACÁ ESTÁ LA MAGIA: El puerto que tu .NET está buscando
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    image: slaccesorios_api
    container_name: slaccesorios_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=slaccesorios_db;Username=postgres;Password=rootpassword
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres_db
    restart: unless-stopped

volumes:
  pgdata: