services:
  db-tech: # Cambiamos el nombre del servicio
    image: postgres:15-alpine
    container_name: slaccesorios # Nombre único para este proyecto
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: slaccesorios_db # Base de datos limpia
    ports:
      - "55432:5432" # <-- MAGIA: Exponemos el puerto 5433 en tu Ubuntu, hacia el 5432 del contenedor
    volumes:
      - slaccesorios_data:/var/lib/postgresql/data # Volumen separado para no pisar el boilerplate
    restart: unless-stopped

volumes:
  slaccesorios_data: