services:
  postgres_db:
    image: postgres:15-alpine
    container_name: slaccesorios_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword # Cambiá esto por algo seguro
      POSTGRES_DB: slaccesorios_db
    ports:
      - "5439:5432" # Expone el 5432 interno de postgres al 5439 de tu máquina Linux
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    image: slaccesorios_api
    container_name: slaccesorios_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expone el puerto de la API
    environment:
      # Sobrescribimos la conexión para que apunte al contenedor de la base de datos, no a localhost
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=slaccesorios_db;Username=postgres;Password=rootpassword
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres_db
    restart: unless-stopped

volumes:
  pgdata: # Este volumen asegura que la base de datos no se borre si apagás el contenedor